/**
 * learning_writer.ts — Daily Learning Note Generator
 *
 * After every task completes, generates a structured Markdown learning
 * note in Memory/learnings/YYYY-MM-DD.md.
 *
 * Appends to existing daily file if multiple tasks complete on the same day.
 * Immediately searchable in Obsidian.
 */

import fs from "fs";
import path from "path";

const ROOT_DIR = path.resolve(__dirname, "..");
const LEARNINGS_DIR = path.join(ROOT_DIR, "Memory", "learnings");

export interface LearningEntry {
    task_id: string;
    project: string;
    title: string;
    connector: string;
    duration_ms: number;
    success: boolean;
    error?: string;
    transitions_count: number;
    quality_score?: number; // 0-10, optional
    notes?: string;
}

/**
 * Get today's date in YYYY-MM-DD format.
 */
function getDateStamp(): string {
    const now = new Date();
    return now.toISOString().split("T")[0];
}

/**
 * Format a learning entry as a Markdown section.
 */
function formatEntry(entry: LearningEntry): string {
    const timestamp = new Date().toISOString().split("T")[1].replace("Z", "");
    const status = entry.success ? "✅ Success" : "❌ Failed";
    const durationSec = (entry.duration_ms / 1000).toFixed(1);

    let md = `\n### ${entry.title}\n\n`;
    md += `| Field | Value |\n`;
    md += `|---|---|\n`;
    md += `| Task ID | \`${entry.task_id}\` |\n`;
    md += `| Project | ${entry.project} |\n`;
    md += `| Connector | ${entry.connector} |\n`;
    md += `| Status | ${status} |\n`;
    md += `| Duration | ${durationSec}s |\n`;
    md += `| Transitions | ${entry.transitions_count} |\n`;

    if (entry.quality_score !== undefined) {
        md += `| Quality Score | ${entry.quality_score}/10 |\n`;
    }

    md += `| Logged At | ${timestamp} |\n`;

    if (entry.error) {
        md += `\n> **Error:** ${entry.error}\n`;
    }

    if (entry.notes) {
        md += `\n**Notes:** ${entry.notes}\n`;
    }

    return md;
}

/**
 * Write a learning entry to the daily learning note.
 * Creates the file if it doesn't exist, appends if it does.
 */
export function writeLearning(entry: LearningEntry): string {
    // Ensure directory exists
    if (!fs.existsSync(LEARNINGS_DIR)) {
        fs.mkdirSync(LEARNINGS_DIR, { recursive: true });
    }

    const dateStamp = getDateStamp();
    const filepath = path.join(LEARNINGS_DIR, `${dateStamp}.md`);
    const entryMd = formatEntry(entry);

    if (fs.existsSync(filepath)) {
        // Append to existing daily file
        fs.appendFileSync(filepath, entryMd, "utf-8");
        console.log(`[learning_writer] Appended to ${dateStamp}.md`);
    } else {
        // Create new daily file with header
        const header = `# Daily Learning Notes — ${dateStamp}\n\n`;
        const meta = `> Auto-generated by BOS Learning Writer.\n> Tasks completed on this day are logged below.\n\n---\n`;
        fs.writeFileSync(filepath, header + meta + entryMd, "utf-8");
        console.log(`[learning_writer] Created ${dateStamp}.md`);
    }

    return filepath;
}

/**
 * Get the count of learnings logged today.
 */
export function getTodayLearningCount(): number {
    const dateStamp = getDateStamp();
    const filepath = path.join(LEARNINGS_DIR, `${dateStamp}.md`);

    if (!fs.existsSync(filepath)) return 0;

    const content = fs.readFileSync(filepath, "utf-8");
    // Count "### " headers (each learning entry starts with one)
    const matches = content.match(/^### /gm);
    return matches ? matches.length : 0;
}
